# Generated by Django 5.1.3 on 2024-11-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='owner',
        ),
    ]
